### ISSUE TITLE
General pages: Ordered list items are not styled.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#37]
![untitled-1order](https://cloud.githubusercontent.com/assets/13309730/13671139/0e0d8646-e6f4-11e5-8f01-8d4c4b4f41ad.png)

**Comment by euveng** [comment]
Fixed.

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
UL list indentations are not styled as stated in design.

![untitled-1-ull](https://cloud.githubusercontent.com/assets/13309730/13740222/8edabe52-e9f5-11e5-9a3d-2ef81d06e7de.png)

**Comment by euveng** [comment]
![admin_general](https://cloud.githubusercontent.com/assets/9030354/13765061/b08399e8-ea90-11e5-9ce1-26738c025705.png)

This was done based on a precedent that was set by QA in Veracity Solutions - see row#9 here: 

https://docs.google.com/spreadsheets/d/1aT2KSg1fwaFy_2l9K-FeeZjMPF01tCnT3myQOXDwsf4/edit#gid=1871997023

Marking this as wontfix.

**Comment by mahender-sowedane** [comment]
it still doesn't seem right to us, it's still going against user expectations
Need to fix.

**Comment by euveng** [comment]
This has been built to standards which I have come to understand from QA's previous assessment. This would take lower priority than user expectations. This will not be fixed.
